module.exports = {
    DefaultPlan: 'Start-Up', // Default plan name
    DefaultRole: 1,
    /* Table names */
    Plan: "plan",
    Cypher: "Cypher",
    HsCode: "HSCodes",
    HsCode: "Test",
    HsCode: "Country",
    export_srilanka: "export_srilanka",
    import_bangladesh: "import_bangladesh",
    export_bangladesh: "export_bangladesh",
    userplantransaction: "userplantransaction",
    export_philip: "export_philip",
    import_srilanka: "import_srilanka",
    import_chile: "import_chile",
    export_ethiopia: "export_ethiopia",
    import_ethiopia: "import_ethiopia",
    export_chile: "export_chile",
    workspace: "workspace",
    import_india: "import_india",
    export_india: "export_india",
    export_turkey:"export_turkey",
    import_turkey:"import_turkey",
    export_russia:"export_russia",
    import_russia:"import_russia",
    Dowload_cost: "Dowload_cost",
    SideFilterAccess: "SideFilterAccess",
    userdownloadtransaction: "userdownloadtransaction",
    import_philip: "import_philip",
    import_usa:"import_usa",
    import_vietnam:"import_vietnam",
    import_kenya:"import_kenya",
    import_lesotho:"import_lesotho",
    import_mexico:"import_mexico",
    import_nigeria:"import_nigeria",
    export_kenya:"export_kenya",
    export_lesotho:"export_lesotho",
    export_mexico:"export_mexico",
    export_nigeria:"export_nigeria",
    export_usa:"export_usa",
    export_vietnam:"export_vietnam",
    /* Select Queries */
    //select_Query_for_totalrecords:'* FROM ',
    select_Query_for_totalrecords:'*, count(*) OVER() AS total_records FROM',
    select_Query_for_totalCounts:'COUNT(distinct  "Exp_Name") as TotalExpName, COUNT(distinct  "Imp_Name") as TotalImpName, COUNT(distinct  "HsCode") as TotalHsCode FROM',
    select_all_to_download:'* FROM',
    india_export_query:'"RecordID", "Type" as "DIRECTION","Date" as "DATE","Month" as "MONTH","Year" as "YEAR","HsCode" as	"TARIFF CODE","HSCode2dig" as "TWO_DIGIT","HSCode4Dig" as "FOUR_DIGIT","ProductDesc" as "ITEM DESCRIPTION","CommodityDesc" as "COMMODITY_DESCRIPTION","uqc"	as "UQC","Quantity" as "QTY","Currency"	as "CURRENCY","UnitPriceFC" as "UNT PRICE FC","InvValueFC" as "EST_VALUE FC","CountryofDestination" as "COUNTRY OF DESTINATION","ValueInUSD" as "EST_ VALUE US$","Exchange_Rate" as "EXCHANGE_RATE","Imp_Name"	as "BUYER","Imp_Address"	as "BUYER ADDRESS","PortofDestination"	as "PORT_OF_DISCHARGE","Mode"	as "MODE_OF_PORT","PortofOrigin"	as "PORT_OF_LODING","Exp_Name"	as "SHIPPER","Exp_Address"	as "SHIPPER ADDRESS","Exp_City"	as "SHIPPER CITY","Exp_PIN"	as "SHIPPER PIN","Exp_Phone"	as "SHIPPER PHONE","Exp_Email"	as "SHIPPER EMAIL","Exp_Contact_Person"	as "SHIPPER CONTACT PERSON" FROM',
    india_import_query:'"RecordID", "Type" as "DIRECTION","Date" as "DATE","Month" as "MONTH","Year" as "YEAR","HsCode" as "TARIFF CODE","HSCode2dig" as "2 DIGIT","HSCode4Dig" as "4 DIGIT","ProductDesc" as "ITEM DESCRIPTION","CommodityDesc" as "COMMODITY DESCRIPITON","uqc" as "UQC","Quantity" as "QTY","Currency" as "CURR","UnitPriceFC" as "UNT PRICE FC","Asset_Value_FC" as "EST VALUE FC","Duty_USD" as "TAX US$ + OTHER CHARGES","Duty_PCNTG" as "TAX %","ValueInUSD" as "EST VALUE US$","Importer_Value_USD" as "TOTAL VALUE US$","Exchange_Rate" as "EXCHANGE RATE","Exp_Name" as "VENDOR","EXPORTER_ADDRESS" as "VENDOR ADDRESS","CountryofOrigin" as "PARTNER COUNTRY","PortofOrigin" as "PORT OF LOADING","PortofDestination" as "PORT OF DISCHARGE","Mode" as "MODE","Imp_Name" as "BUYER","Importer_Address" as "BUYER ADDRESS","Importer_City" as "BUYER CITY","Importer_PIN" as "BUYER PIN","Importer_Phone" as "BUYER PHONE","Importer_Email" as "BUYER EMAIL","Importer_Contact_Person" as "BUYER CONTACT PERSON","BE_Type" as "BE TYPE","CHA_Name" as "NOTIFY PARTY NAME" FROM',
    /* Mail Configuration */
    // fromEmail:'webeximpanel@gmail.com',
    // fromPassword:'gayrsqtbgrlvltit',
    fromEmail:'no-reply@myeximpanel.com',
    fromPassword:'Dollar$1234@',
    userRegisterationmailSubject:'User Registered Successfully !',
    userUpdatemailSubject:'User Updated Successfully !',
    accountcreationmailBody:'Congratulations! Your account has been created successfully.\nYour password is the first five letters of your first name, followed by the last five digits of your contact number.\n\ne.g Jayesh Patel 9890101234 \nso password will be Jayes01234\n\nThank you for showing your trust in our services. Your satisfaction is our priority, and we will continue to strive to provide you with the highest quality products and services. We look forward to continuing to build our relationship and for the opportunities that lie ahead. If you have any questions or concerns, please do nott hesitate to contact us.'
}
